name: CI

on:
  push:
  pull_request:
  workflow_dispatch:  # allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - name: Checkout codebase
      uses: actions/checkout@v4
    
    - name: Set up node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.node-version}}
    
    - name: Install dependencies
      run: npm install
    
    - name: run unit tests
      run: npm test && npm run coverage 
      github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run coverage and export to Coveralls
      uses: coverallsapp/github-action@v2